Update padavan-PSG1218.yml

diff --git a/.github/workflows/padavan-PSG1218.yml b/.github/workflows/padavan-PSG1218.yml
--- a/.github/workflows/padavan-PSG1218.yml
+++ b/.github/workflows/padavan-PSG1218.yml
@@ -1,101 +1,114 @@
-# # # # # # # # # # #
-#  自动构建 PSG1218
-#     花妆男
-# # # # # # # # # # #
-name: Padavan CI PSG1218
-on:
-  # schedule:                           # 时间表
-  #   - cron: '0 19 * * *'              # 每天国际时间19点，北京时间凌晨3点执行(北京+8)
-  push:                               # push 操作
-    branches:                         # 分支
-      - master                        # 主分支
-  #   paths:                            # 路径
-  #     - openwrt/*                     # 监听openwrt目录下所有文件的push操作
-    paths:                            # 路径
-      - logs/k2.md                    # 监听logs目录下 k2.md 的push操作
-  watch:                              # 监视操作
-    types: [started]                  # 点击 star 之后
-env:
-  T_NAMES: "PSG1218"        # 设备名字数组
-  BASE_PATH: padavan                # 基础目录
-  PUBLIC_PATH: public               # 公共目录
-  VERSION_FILE: versions.inc        # 版本后缀
-  PUBLIC_SH: public.sh              # 公共命令
-  UPLOAD_FIRMWARE: true             # 是否打包文件
-  CLONE_URL: https://github.com/chongshengB/rt-n56u.git # padavan  地址
-  CLONE_BRANCH: master              # padavan 分支
-  WORK_PATH: /opt/rt-n56u           # 工作目录 一定要加 /
+#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
+name: Build Padavan
+
+on: 
+  release:
+    types: [published]
+  push:
+    tags:
+    - 'v*'
+  #  branches: 
+  #    - master
+#  schedule:
+#    - cron: 0 8 * * 5
+  watch:
+    types: [started]
+
 jobs:
   build:
     runs-on: ubuntu-18.04
-    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
+    if: github.event.repository.owner.id == github.event.sender.id
+
     steps:
-    - name: Checkout Master            # 1.导入主分支
+    - name: Checkout
       uses: actions/checkout@master
-    - name: Initialization Environment # 2.初始环境的设置
+    - name: Initialization environment
       env:
-        DEBIAN_FRONTEND: noninteractive  # 非交互模式
+        DEBIAN_FRONTEND: noninteractive
       run: |
-        sudo apt-get clean
-        cd /var/lib/apt
-        sudo mv lists lists.old
-        sudo mkdir -p lists/partial
-        sudo apt-get clean
         sudo apt-get update
-        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
+        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
         cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
-        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev gcc-multilib
-        sudo timedatectl set-timezone 'Asia/Shanghai'  # 设置时区
-    - name: Clone Code                 # 3.拷贝代码
+        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
+    - name: Clone source code
       run: |
-        git clone --depth=1 $CLONE_URL -b $CLONE_BRANCH $WORK_PATH
-    - name: Build Tool Chain           # 4.构建工具链
-      run: |
-        cd $WORK_PATH/toolchain-mipsel
+        git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
+        cd /opt/rt-n56u/toolchain-mipsel
         sh dl_toolchain.sh
-        mkdir -p ${WORK_PATH}/images/
-    - name: Clear And Build            # 5.清理构建树并开始构建
+        mkdir -p /opt/images/
+    
+    - name: Build Firmware
+      env:
+        TNAME: PSG1218_hzn
       run: |
-        cwd=`pwd`
-        CONFIG_TOOLCHAIN_DIR=${cwd//\//\\\/}\\/toolchain-mipsel
-        # 1.拷贝公共文件
-        cp -f $BASE_PATH/$PUBLIC_PATH/$PUBLIC_SH  $WORK_PATH/
-        sudo chmod +x $WORK_PATH/$PUBLIC_SH
-        # 2. 循环替换自定义默认模板和构建，单个设备的 sh 拷贝 t_item 需要编译的固件名字
-        for t_item in $T_NAMES;
-        do
-        if [ ! -e $BASE_PATH/$t_item/$t_item.config ] ; then
-          echo "${BASE_PATH}/${t_item}/${t_item}.config 自定义模板文件未找到"
+        if [ -f public/shadowsocks.sh ] ; then
+        mv -f public/shadowsocks.sh /opt/rt-n56u/trunk/user/shadowsocks/scripts/shadowsocks.sh
+        echo "shadowsocks SH copy success"
         else
-          cp -f $BASE_PATH/$t_item/$t_item.config $WORK_PATH/trunk/configs/templates/$t_item.config
-          echo "${t_item} 修改模板完成"
-        fi
-        if [ ! -f $BASE_PATH/$t_item/$t_item.sh ] ; then
-          echo "${BASE_PATH}/${t_item}/${t_item}.sh 自定义SH文件未找到"
+        exit 1
+        fi 
+        if [ -f public/PSG1218_hzn.config ] ; then
+        mv -f public/PSG1218_hzn.config /opt/rt-n56u/trunk/configs/templates/PSG1218_hzn.config
+        echo "config file copy success"
         else
-          cp -f $BASE_PATH/$t_item/$t_item.sh  $WORK_PATH/
-          sudo chmod +x $WORK_PATH/$t_item.sh
-          echo "${t_item} 自定义SH文件拷贝成功"
+        exit 2
+        fi 
+        cd /opt/rt-n56u/trunk
+        if [ ! -f configs/templates/$TNAME.config ] ; then
+        echo "configs/templates/$TNAME.config not found "
+        exit 3
         fi
-        if [ -f $BASE_PATH/$t_item/shadowsocks.sh ] ; then
-          mv -f $BASE_PATH/$t_item/shadowsocks.sh $WORK_PATH/trunk/user/shadowsocks/scripts/shadowsocks.sh
-          echo "${t_item} SSPlus SH文件拷贝成功"
-        fi
-        done
-        # 3. 开始构建
-        cd $WORK_PATH/trunk
-        for t_item in $T_NAMES;
-        do
-        cp -f configs/templates/$t_item.config .config  # 拷贝模板到 .config
-        echo "执行 ${PUBLIC_SH} sh"
-        sudo $WORK_PATH/$PUBLIC_SH
-        if [ -e $WORK_PATH/$t_item.sh ] ; then
-          echo "执行自定义 ${t_item} sh"
-          sudo $WORK_PATH/$t_item.sh
-        fi
-        # 4. 清理构建
-        sed -i "s/^CONFIG_TOOLCHAIN_DIR=.*$/CONFIG_TOOLCHAIN_DIR=${CONFIG_TOOLCHAIN_DIR}/g" .config
-        sudo cp -f .config ${WORK_PATH}/images/
+        cp -f configs/templates/$TNAME.config .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
+        ################################################################################################
+        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
+        ################################################################################################
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #删除配置项MENTOHUST
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #删除配置项SCUTCLIENT
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #删除配置项SS plus+
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSOBFS/d' .config # 删除配置项simple-obfs混淆插件
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #删除配置项SS server
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项DNSFORWARDER
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #删除配置项adbyby plus+
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #删除配置项adbyby plus+
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #删除配置项adbyby plus+
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #删除配置项adbyby plus+
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #删除配置项阿里DDNS
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
+        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
+        ######################################################################
+        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
+        ######################################################################
+        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
+        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
+        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config #SS plus+
+        echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=y" >> .config # simple-obfs混淆插件
+        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
+        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
+        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config #去广告adbyby plus+
+        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config #内网穿透FRPC
+        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #内网穿透FRPS
+        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
+        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #阿里DDNS
+        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config #smartdns
+        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config #smartdns二进制文件
+        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #集成v2ray执行文件（3.8M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
+        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #集成trojan执行文件(1.1M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
+        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config #KP广告过滤
+        echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config #在线文件管理服务
+        echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #集成caddu执行文件，此文件有13M,请注意固件大小。如果不集成，会从网上下载下来执行，不影响正常使用
+        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config
+        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #可以不集成
+        echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config #网易云解锁
+        echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #网易云解锁GO版本执行文件（4M多）注意固件超大小,不集成会自动下载
+        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
+        #########################################################################################
+        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
+        #格式如下：
+        #sed -i '/自定义项/d' .config
+        #echo "自定义项=y" >> .config
+        #########################################################################################
         sudo ./clear_tree
         sudo ./build_firmware_modify $TNAME 0
         sudo mv -f images/*.trx /opt/images/
